# Site settings
title: Johannes Elias Lohbihler
email: mail@lohbihler.com
description: > # this means to ignore newlines until "baseurl:"
  Is a creative studio and production facility located in the heart of Berlin. We conceptualize, develop and produce creative and interactive experiences for large and small clients. With a strong emphasis on prototyping we quickly iterate over software and hardware to deliver innovative solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lohbihler.com" # the base hostname & protocol for your site
twitter:
  username: nevvkid

# Google analytics
google_analytics: UA-87258531-1

# Build settings
markdown: kramdown

# SASS settings
sass:
    style: compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
