# Site settings
title: Johannes Elias Lohbihler
email: mail@lohbihler.com
description: > # this means to ignore newlines until "baseurl:"
  Is a Creative Technologist living and working in Berlin. Currently running solution.io. Creator of dadamachines. Previously co-founder of a SaaS company named LUXOWORKS. He is a seventh generation carpenter with a BA in product design and an MA in interaction design. He creates digital and analogue products and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://lohbihler.com   # with the https protocol
enforce_ssl: lohbihler.com   # without any protocol
twitter:
  username: nevvkid

# Google analytics
google_analytics: UA-87258531-1

# Build settings
markdown: kramdown

# SASS settings
sass:
    style: compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
